language: php

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-8.1.phar

script:
  - vendor/bin/phpunit --verbose
